source 'https://rubygems.org'

ruby '3.0.2'

gem 'capybara'
gem 'cucumber'
gem 'selenium-webdriver', '~> 4.11.0'
gem 'geckodriver-helper', '~> 0.0.5'
gem 'site_prism'
gem 'rspec'
gem 'rspec-retry'
gem 'dotenv'
gem 'csv'
gem 'racc'
gem 'nokogiri'
gem 'actionview'
gem 'httparty'
gem 'json-schema-rspec'
gem 'json-schema'
gem 'json_matchers'
gem 'jsonpath'
gem 'json'
gem 'pdf-reader'
gem 'spreadsheet'
gem 'write_xlsx'
gem 'fileutils'
gem 'google-cloud-storage'
gem 'roo'
gem 'faker'
gem 'securerandom'
